<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class PropertiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('properties')->truncate();
        DB::table('properties')->insert([
        	[
	            "title" => "2 bedroom Condo for sale in Samut Prakan",
                "description" => "Unde sunt quam doloremque nihil ut velit et ipsum. Dolorum magnam voluptas vel ipsa impedit quo repudiandae. Praesentium sapiente libero harum occaecati beatae tempora.",
                "for_sale" => true,
                "for_rent" => false,
                "sold" => false,
                "price" => 635933,
                "currency" => "THB",
                "currency_symbol" => "\u0e3f",
                "property_type" => "Condo",
                "bedrooms" => 2,
                "bathrooms" => 5,
                "area" => 87,
                "area_type" => "sqm",
            ],
            [
	            "title" => "1 bedroom Apartment for sale in Phuket",
                "description" => "Harum impedit consequuntur omnis magnam minima. Dignissimos illo quidem laboriosam et. Qui maiores eveniet rerum sit.",
                "for_sale" => true,
                "for_rent" => false,
                "sold" => false,
                "price" => 635933,
                "currency" => "THB",
                "currency_symbol" => "\u0e3f",
                "property_type" => "Apartment",
                "bedrooms" => 2,
                "bathrooms" => 5,
                "area" => 87,
                "area_type" => "sqm",
            ],
            [
	            "title" => "2 bedroom Villa for rent in Bangkok",
                "description" => "Sit et in repellat. Ut facere doloribus eos saepe occaecati nulla. At veniam sit voluptatem inventore sit est.",
                "for_sale" => true,
                "for_rent" => false,
                "sold" => false,
                "price" => 635933,
                "currency" => "THB",
                "currency_symbol" => "\u0e3f",
                "property_type" => "Apartment",
                "bedrooms" => 2,
                "bathrooms" => 5,
                "area" => 87,
                "area_type" => "sqm",
            ],
            [
	            "title" => "2 bedroom Villa for rent in Bangkok",
                "description" => "Sit et in repellat. Ut facere doloribus eos saepe occaecati nulla. At veniam sit voluptatem inventore sit est.",
                "for_sale" => true,
                "for_rent" => false,
                "sold" => false,
                "price" => 635933,
                "currency" => "THB",
                "currency_symbol" => "\u0e3f",
                "property_type" => "Apartment",
                "bedrooms" => 2,
                "bathrooms" => 5,
                "area" => 87,
                "area_type" => "sqm",
            ],
            [
	            "title" => "5 bedroom Townhouse for sale in Chiang Mai",
                "description" => "Qui porro fugiat unde et aliquid. Sapiente eos culpa sunt animi sed voluptatem doloremque. Dolores quos aut ex dolores deserunt rerum nihil",
                "for_sale" => true,
                "for_rent" => false,
                "sold" => false,
                "price" => 635933,
                "currency" => "THB",
                "currency_symbol" => "\u0e3f",
                "property_type" => "Apartment",
                "bedrooms" => 2,
                "bathrooms" => 5,
                "area" => 87,
                "area_type" => "sqm",
            ],
            [
	            "title" => "2 bedroom Apartment for sale in Chon Buri",
                "description" => "Ut alias amet saepe saepe amet nam. Quae qui aut in doloremque. Vel eligendi fugiat beatae et voluptates ut consequatur rerum.",
                "for_sale" => true,
                "for_rent" => false,
                "sold" => false,
                "price" => 635933,
                "currency" => "THB",
                "currency_symbol" => "\u0e3f",
                "property_type" => "Apartment",
                "bedrooms" => 2,
                "bathrooms" => 5,
                "area" => 87,
                "area_type" => "sqm",
            ],
            [
	            "title" => "2 bedroom House for rent in Chiang Mai",
                "description" => "Aut impedit aut dolorem eos. Ducimus asperiores possimus nisi repudiandae expedita saepe impedit corrupti. Recusandae aut quod enim unde aut.",
                "for_sale" => true,
                "for_rent" => false,
                "sold" => false,
                "price" => 635933,
                "currency" => "THB",
                "currency_symbol" => "\u0e3f",
                "property_type" => "Apartment",
                "bedrooms" => 2,
                "bathrooms" => 5,
                "area" => 87,
                "area_type" => "sqm",
            ],
            [
	            "title" => "2 bedroom Condo for sale in Surat Thani",
                "description" => "Sit et in repellat. Ut facere doloribus eos saepe occaecati nulla. At veniam sit voluptatem inventore sit est.",
                "for_sale" => true,
                "for_rent" => false,
                "sold" => false,
                "price" => 635933,
                "currency" => "THB",
                "currency_symbol" => "\u0e3f",
                "property_type" => "Apartment",
                "bedrooms" => 2,
                "bathrooms" => 5,
                "area" => 87,
                "area_type" => "sqm",
            ],
            [
	            "title" => "2 bedroom Condo for sale in Chon Buri",
                "description" => "Sit et in repellat. Ut facere doloribus eos saepe occaecati nulla. At veniam sit voluptatem inventore sit est.",
                "for_sale" => true,
                "for_rent" => false,
                "sold" => false,
                "price" => 635933,
                "currency" => "THB",
                "currency_symbol" => "\u0e3f",
                "property_type" => "Apartment",
                "bedrooms" => 2,
                "bathrooms" => 5,
                "area" => 87,
                "area_type" => "sqm",
            ],
            [
	            "title" => "2 bedroom Villa for rent in Bangkok",
                "description" => "Sit et in repellat. Ut facere doloribus eos saepe occaecati nulla. At veniam sit voluptatem inventore sit est.",
                "for_sale" => true,
                "for_rent" => false,
                "sold" => false,
                "price" => 635933,
                "currency" => "THB",
                "currency_symbol" => "\u0e3f",
                "property_type" => "Apartment",
                "bedrooms" => 2,
                "bathrooms" => 5,
                "area" => 87,
                "area_type" => "sqm",
            ],

	    ]);
    }
}